name: critical_test
version: 7.0.1
homepage: https://www.noojee.dev
documentation: https://criticaltest.noojee.dev
description: Critical Test is a cli tool designed to simplify the process of fixing broken unit tests in Dart.
repository: https://github.com/bsutton/critical_tester
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  _fe_analyzer_shared: 50.0.0
  analyzer: 5.2.0
  archive: 3.3.4
  args: 2.3.1
  async: 2.10.0
  basic_utils: 3.9.4
  boolean_selector: 2.1.1
  build: 2.3.1
  build_config: 1.1.1
  build_daemon: 3.1.0
  build_resolvers: 2.1.0
  build_runner_core: 7.2.7
  built_collection: 5.1.1
  built_value: 8.4.2
  charcode: 1.3.1
  checked_yaml: 2.0.1
  circular_buffer: 0.11.0
  cli_script: 0.2.6
  code_builder: 4.3.0
  collection: 1.17.0
  convert: 3.1.1
  coverage: 1.6.1
  crypto: 3.0.2
  csv: 5.0.1
  dart_style: 2.2.4
  dcli: 1.35.7
  dcli_core: 1.35.7
  equatable: 2.0.5
  ffi: 2.0.0
  file: 6.1.4
  fixnum: 1.0.1
  frontend_server_client: 3.1.0
  glob: 2.1.1
  graphs: 2.2.0
  http: 0.13.5
  http_multi_server: 3.2.1
  http_parser: 4.0.2
  ini: 2.1.0
  io: 1.0.3
  js: 0.6.5
  json_annotation: 4.7.0
  logging: 1.1.0
  matcher: 0.12.13
  meta: 1.8.0
  mime: 1.0.2
  node_preamble: 2.0.1
  package_config: 2.1.0
  path: 1.8.2
  pedantic: 1.11.1
  pointycastle: 3.6.2
  pool: 1.5.1
  posix: 4.1.0
  pub_semver: 2.1.3
  pubspec: 2.3.0
  pubspec_parse: 1.2.1
  quiver: 3.1.0
  random_string: 2.3.1
  scope: 3.0.0
  settings_yaml: 4.0.1
  shelf: 1.4.0
  shelf_packages_handler: 3.0.1
  shelf_static: 1.1.1
  shelf_web_socket: 1.0.3
  source_map_stack_trace: 2.1.1
  source_maps: 0.10.11
  source_span: 1.9.1
  stack_trace: 1.11.0
  stacktrace_impl: 2.3.0
  stream_channel: 2.1.1
  stream_transform: 2.1.0
  string_scanner: 1.2.0
  term_glyph: 1.2.1
  test_api: 0.4.16
  test_core: 0.4.20
  timing: 1.0.0
  tuple: 2.0.1
  typed_data: 1.3.1
  uri: 1.0.0
  uuid: 3.0.7
  validators2: 3.0.0
  vin_decoder: 0.2.1-nullsafety
  vm_service: 9.4.0
  watcher: 1.0.2
  web_socket_channel: 2.2.0
  webkit_inspection_protocol: 1.2.0
  win32: 3.1.1
  yaml: 3.1.1
dev_dependencies: 
  build_runner: ^2.2.0
  lint_hard: ^2.0.0
  test: ^1.0.0
executables: 
  critical_test: 
  ct: critical_test
