name: critical_test
version: 6.0.2
homepage: https://www.noojee.dev
documentation: https://criticaltest.noojee.dev
description: Critical Test is a cli tool designed to simplify the process of fixing broken unit tests in Dart.
repository: https://github.com/bsutton/critical_tester
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  args: ^2.3.1
  cli_script: ^0.2.6
  dcli: ^1.34.0
  json_annotation: ^4.6.0
  meta: ^1.8.0
  path: ^1.8.2
  settings_yaml: ^3.4.1
  win32: ^2.0.5
dev_dependencies: 
  build_runner: ^2.2.0
  lint_hard: ^2.0.0
  test: ^1.0.0
executables: 
  critical_test: 
  ct: critical_test
