name: critical_test
version: 0.0.2
description: Critical Test is a cli tool designed to simplify the process of fixing broken unit tests in Dart.
repository: https://github.com/bsutton/critical_tester

environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  args: ^2.0.0
  dcli: ^1.0.0
  path: ^1.8.0
dev_dependencies: 
  pedantic: ^1.0.0
  test: ^1.0.0
# dependency_overrides: 
#   dcli: 
#     path: ../dcli
executables: 
  critical_test: critical_test
