name: critical_test
version: 8.0.0
homepage: https://www.noojee.dev
documentation: https://criticaltest.noojee.dev
description: Critical Test is a cli tool designed to simplify the process of fixing broken unit tests in Dart.
repository: https://github.com/bsutton/critical_tester

environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  _fe_analyzer_shared: ^68.0.0
  analyzer: ^6.5.0
  archive: ^3.3.7
  args: ^2.4.1
  async: ^2.11.0
  basic_utils: ^5.7.0
  boolean_selector: 2.1.1
  build: ^2.4.0
  build_config: 1.1.1
  build_daemon: ^4.0.0
  build_resolvers: ^2.2.0
  build_runner_core: ^7.2.8
  built_collection: 5.1.1
  built_value: ^8.5.0
  charcode: 1.3.1
  checked_yaml: ^2.0.3
  circular_buffer: 0.11.0
  cli_script: ^1.0.0
  code_builder: ^4.4.0
  collection: ^1.17.2
  convert: 3.1.1
  coverage: ^1.6.3
  crypto: ^3.0.3
  csv: ^5.1.1
  dart_style: ^2.2.5
  dcli: ^2.2.0
  dcli_core: ^2.2.0
  equatable: 2.0.5
  ffi: ^2.0.1
  file: ^7.0.0
  fixnum: ^1.1.0
  frontend_server_client: ^4.0.0
  glob: ^2.1.2
  graphs: ^2.3.0
  http: ^1.2.1
  http_multi_server: 3.2.1
  http_parser: ^4.1.0
  ini: 2.1.0
  io: ^1.0.4
  js: ^0.7.1
  json_annotation: ^4.8.1
  logging: ^1.1.1
  matcher: ^0.12.14
  meta: ^1.9.1
  mime: ^1.0.4
  node_preamble: ^2.0.2
  package_config: 2.1.0
  path: ^1.8.3
  pedantic: 1.11.1
  pointycastle: ^3.7.3
  pool: 1.5.1
  posix: ^6.0.1
  pub_semver: ^2.1.4
  pubspec: 2.3.0
  pubspec_parse: ^1.2.3
  quiver: ^3.2.1
  random_string: 2.3.1
  scope: ^4.1.0
  settings_yaml: ^8.1.0
  shelf: ^1.4.1
  shelf_packages_handler: ^3.0.2
  shelf_static: ^1.1.2
  shelf_web_socket: ^2.0.0
  source_map_stack_trace: 2.1.1
  source_maps: ^0.10.12
  source_span: ^1.10.0
  stack_trace: ^1.11.1
  stacktrace_impl: 2.3.0
  stream_channel: ^2.1.2
  stream_transform: 2.1.0
  string_scanner: 1.2.0
  term_glyph: 1.2.1
  timing: ^1.0.1
  tuple: ^2.0.2
  typed_data: ^1.3.2
  uri: 1.0.0
  uuid: ^4.4.0
  validators2: ^5.0.0
  vm_service: ^14.2.4
  watcher: ^1.1.0
  web_socket_channel: ^3.0.0
  webkit_inspection_protocol: ^1.2.1
  win32: any
  yaml: ^3.1.2
dev_dependencies:
  build_runner: ^2.2.0
  lint_hard: ^4.0.0
  test: ^1.0.0
  test_api: ^0.7.3
  test_core: ^0.6.5
executables:
  critical_test:
  ct: critical_test
