name: critical_test
version: 5.1.3
homepage: https://www.noojee.dev
documentation: https://criticaltest.noojee.dev
description: Critical Test is a cli tool designed to simplify the process of fixing broken unit tests in Dart.
repository: https://github.com/bsutton/critical_tester
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  args: ^2.0.0
  cli_script: ^0.2.0
  dcli: ^1.10.0
  json_annotation: ^4.1.0
  meta: ^1.0.0
  path: ^1.8.0
  settings_yaml: ^3.0.6
dev_dependencies: 
  build_runner: ^2.0.0
  lints: ^1.0.0
  test: ^1.0.0
  json_serializable: ^6.0.1
dependency_overrides: 
  dcli: 
    path: ../dcli
executables: 
  critical_test: critical_test
